name: Full Archive CI
on:
  schedule:
    - cron: "0 13 * * 1" # run every monday

jobs: 
  cloud-tests:
    name: Build (cloud-data-tests | ${{ matrix.variable_id }} | ${{ matrix.experiment_id }} | ${{ matrix.grid_label }})
    strategy:
      fail-fast: false
      matrix:
        variable_id: ["thetao", "o2", "so"]
        experiment_id: ["historical", "piControl", "ssp585"]
        grid_label: ["gn", "gr"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if ci/environment-upstream-dev.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('ci/environment-upstream-dev.yml') }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge, defaults
        activate-environment: test_env_cmip6_preprocessing # Defined in ci/environment-upstream-dev.yml
        auto-update-conda: false
        python-version: 3.8
        environment-file: ci/environment-cloud-test.yml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: Set up conda environment
      shell: bash -l {0}
      run: |
        python -m pip install -e .
        conda list
    - name: Run Tests
      shell: bash -l {0}
      run: |
        pwd
        echo $PYTHONPATH
        pytest --maxfail 5 cmip6_preprocessing/tests/test_preprocessing_cloud.py --gl ${{ matrix.grid_label }} --ei ${{ matrix.experiment_id }} --vi ${{ matrix.variable_id }}
